edcprovider:
  participant:
    id: provider
  vault:
    hashicorp:
      token: "XXXXXX"
  controlplane:
    endpoints:
      management:
        authKey: "XXXXXX"
  backendService:
    httpProxyTokenReceiverUrl: "XXXXXX"


edcconsumer:
  participant:
    id: consumer
  vault:
    hashicorp:
      token: "XXXXXX"
